/**
 * Graph-related types shared between:
 * - Supabase Edge Functions (Deno)
 * - Next.js tRPC routers (Node.js)
 * - Frontend components (Browser)
 */

import type { BaseEntity } from './types.ts';

// ============================================
// RELATIONSHIP TYPES
// ============================================

/**
 * Types of relationships between contacts
 */
export type RelationshipType =
  | 'colleague'
  | 'friend'
  | 'mentor'
  | 'mentee'
  | 'client'
  | 'investor'
  | 'partner'
  | 'acquaintance'
  | 'collaborator'
  | 'reports_to'
  | 'family'
  | 'other';

/**
 * Contact-to-contact relationship stored in Supabase
 */
export interface ContactRelationship extends BaseEntity {
  id: string; // UUID
  from_contact_id: string;
  to_contact_id: string;
  type: RelationshipType;
  strength: number; // 1-5
  notes?: string | null;
  since?: string | null; // ISO date
  introduced_by_contact_id?: string | null;

  // Sync status
  synced_to_arango?: boolean;
  arango_edge_key?: string | null;
  last_synced_at?: string | null;

  // Audit
  created_by?: string | null;
}

// ============================================
// ARANGO TYPES (for sync operations)
// ============================================

/**
 * Person node in ArangoDB
 */
export interface ArangoPersonNode {
  _key: string; // UUID from Supabase
  name: string;
  email?: string;
  type: 'person';
  source: 'supabase';
  synced_at: string; // ISO timestamp
}

/**
 * Company node in ArangoDB
 */
export interface ArangoCompanyNode {
  _key: string; // UUID from Supabase
  name: string;
  domain?: string;
  type: 'company';
  source: 'supabase';
  synced_at: string;
}

/**
 * Relationship edge in ArangoDB knows collection
 */
export interface ArangoKnowsEdge {
  _key?: string; // Auto-generated by ArangoDB if not provided
  _from: string; // "persons/uuid"
  _to: string; // "persons/uuid"
  type: RelationshipType;
  strength: number;
  cost: number; // 1/strength for path-finding
  notes?: string;
  since?: string;
  introduced_by?: string; // "persons/uuid"
}

// ============================================
// SYNC TYPES
// ============================================

/**
 * Entity types that can be synced
 */
export type GraphEntityType = 'contact' | 'company' | 'relationship';

/**
 * Sync operations
 */
export type GraphSyncOperation = 'create' | 'update' | 'delete';

/**
 * Sync status
 */
export type GraphSyncStatus = 'success' | 'failed' | 'pending';

/**
 * Log entry for sync operations
 */
export interface GraphSyncLog extends BaseEntity {
  id: string;
  entity_type: GraphEntityType;
  entity_id: string;
  operation: GraphSyncOperation;
  status: GraphSyncStatus;
  error_message?: string | null;
  arango_collection?: 'persons' | 'companies' | 'knows';
  arango_key?: string | null;
}

/**
 * Mapping between Supabase entities and ArangoDB nodes
 */
export interface GraphEntityMapping extends BaseEntity {
  id: string;
  supabase_table: 'backoffice_contacts' | 'backoffice_companies';
  supabase_id: string;
  arango_collection: 'persons' | 'companies';
  arango_key: string;
  first_synced_at?: string;
  last_synced_at?: string;
  sync_count?: number;
}

// ============================================
// WEBHOOK PAYLOAD (for edge function)
// ============================================

/**
 * Payload sent to sync-to-graph edge function
 */
export interface SyncWebhookPayload {
  type: 'INSERT' | 'UPDATE' | 'DELETE';
  table: string;
  record: any;
  old_record?: any;
}

// ============================================
// NETWORK VISUALIZATION TYPES
// ============================================

/**
 * Node in network graph (for Cytoscape.js)
 */
export interface NetworkNode {
  id: string;
  label: string;
  type: 'person' | 'company';
  tags?: string[];
}

/**
 * Edge in network graph
 */
export interface NetworkEdge {
  id?: string;
  source: string;
  target: string;
  type: string;
  strength?: number;
}

/**
 * Complete network data
 */
export interface NetworkData {
  nodes: NetworkNode[];
  edges: NetworkEdge[];
}

// ============================================
// QUERY INPUT/OUTPUT TYPES
// ============================================

/**
 * Input for ego network query
 */
export interface EgoNetworkInput {
  contact_id: string;
  depth?: number; // 1-3
  include_companies?: boolean;
}

/**
 * Input for path finding
 */
export interface FindPathInput {
  from_contact_id: string;
  to_contact_id: string;
  max_depth?: number; // 1-5
}

/**
 * Path node in result
 */
export interface PathNode {
  person: {
    id: string;
    name: string;
  };
  edge: {
    type: string;
    strength: number;
  } | null;
}

/**
 * Path result with recommendation
 */
export interface PathResult {
  path: PathNode[];
  score: number;
  recommendation: {
    level: 'warm' | 'medium' | 'cold';
    message: string;
  };
}

/**
 * Input for mutual connections
 */
export interface MutualConnectionsInput {
  contact1_id: string;
  contact2_id: string;
}

/**
 * Mutual connection result
 */
export interface MutualConnection {
  person: {
    id: string;
    name: string;
    email?: string;
  };
  your_strength: number;
  their_strength: number;
  avg_strength: number;
  your_type: string;
  their_type: string;
}

// ============================================
// NETWORK STATISTICS
// ============================================

/**
 * Network statistics for a contact (from view)
 */
export interface ContactNetworkStats {
  id: string;
  first_name: string;
  last_name: string | null;
  outbound_connections: number;
  inbound_connections: number;
  total_connections: number;
  avg_outbound_strength: number | null;
  avg_inbound_strength: number | null;
  strong_connections: number;
  synced_to_graph: boolean;
  last_graph_sync_at: string | null;
}

/**
 * Relationship type statistics (from view)
 */
export interface RelationshipTypeStats {
  type: RelationshipType;
  count: number;
  avg_strength: number;
  synced_count: number;
  pending_sync_count: number;
}

/**
 * Sync health metrics (from view)
 */
export interface GraphSyncHealth {
  entity_type: GraphEntityType;
  total_operations: number;
  successful: number;
  failed: number;
  pending: number;
  success_rate: number;
  last_sync_attempt: string | null;
}
